name: Create Change Request

on:
  issues:
    types: [labeled]

jobs:
  create-cr:
    if: contains(github.event.issue.labels.*.name, 'trigger-cr')
    runs-on: ubuntu-latest
    steps:
      - name: Echo Selected PRs
        run: echo "${{ github.event.issue.body }}"

