name: Create Change Request

on:
  issues:
    types: [opened]

jobs:
  create-cr:
    if: github.event.issue.title == 'Select PRs for Change Request'
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Body
        run: echo "${{ github.event.issue.body }}"

      # Add your CR creation logic here
